### PR TITLE
Add the MIT license

### PR DESCRIPTION
**Pull request by Panquesito7**
### Describe the changes you've made

- Add the MIT license.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

I don't think this applies here.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |
 
## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/web3community/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by krishguptadev — COMMENTED** [review]
As per the discussion in the discord server, we are gonna allow people to propose articles as a PR. We'll be adding a more restrictive license to make sure the author gets the right.

**Comment by Panquesito7** [comment]
> As per the discussion in the discord server, we are gonna allow people to propose articles as a PR. We'll be adding a more restrictive license to make sure the author gets the right.

Do you think AGPLv3.0+ would be good?

**Comment by krishguptadev** [comment]
> > As per the discussion in the discord server, we are gonna allow people to propose articles as a PR. We'll be adding a more restrictive license to make sure the author gets the right.
> 
> Do you think AGPLv3.0+ would be good?

We need something in the CC line, like we did for Branding

**Comment by Panquesito7** [comment]
> > > As per the discussion in the discord server, we are gonna allow people to propose articles as a PR. We'll be adding a more restrictive license to make sure the author gets the right.
> > 
> > 
> > Do you think AGPLv3.0+ would be good?
> 
> We need something in the CC line, like we did for Branding

Those are strict (depends on which one you choose), but not as strict as the AGPLv3.0+, AFAIK.

**Comment by krishguptadev** [comment]
> > > > As per the discussion in the discord server, we are gonna allow people to propose articles as a PR. We'll be adding a more restrictive license to make sure the author gets the right.
> > > 
> > > 
> > > Do you think AGPLv3.0+ would be good?
> > 
> > 
> > We need something in the CC line, like we did for Branding
> 
> Those are strict (depends on which one you choose), but not as strict as the AGPLv3.0+, AFAIK.

But I believe content on the internet is licensed under CC something...

**Comment by Panquesito7** [comment]
> > > > > As per the discussion in the discord server, we are gonna allow people to propose articles as a PR. We'll be adding a more restrictive license to make sure the author gets the right.
> > > > 
> > > > 
> > > > Do you think AGPLv3.0+ would be good?
> > > 
> > > 
> > > We need something in the CC line, like we did for Branding
> > 
> > 
> > Those are strict (depends on which one you choose), but not as strict as the AGPLv3.0+, AFAIK.
> 
> But I believe content on the internet is licensed under CC something...

Yeah. Both of them can be used. 😄

**Comment by krishguptadev** [comment]
> > > > > > As per the discussion in the discord server, we are gonna allow people to propose articles as a PR. We'll be adding a more restrictive license to make sure the author gets the right.
> > > > > 
> > > > > 
> > > > > Do you think AGPLv3.0+ would be good?
> > > > 
> > > > 
> > > > We need something in the CC line, like we did for Branding
> > > 
> > > 
> > > Those are strict (depends on which one you choose), but not as strict as the AGPLv3.0+, AFAIK.
> > 
> > 
> > But I believe content on the internet is licensed under CC something...
> 
> Yeah. Both of them can be used. 😄

Cool! I'll add the licenses

**Comment by Panquesito7** [comment]
> > > > > > > As per the discussion in the discord server, we are gonna allow people to propose articles as a PR. We'll be adding a more restrictive license to make sure the author gets the right.
> > > > > > 
> > > > > > 
> > > > > > Do you think AGPLv3.0+ would be good?
> > > > > 
> > > > > 
> > > > > We need something in the CC line, like we did for Branding
> > > > 
> > > > 
> > > > Those are strict (depends on which one you choose), but not as strict as the AGPLv3.0+, AFAIK.
> > > 
> > > 
> > > But I believe content on the internet is licensed under CC something...
> > 
> > 
> > Yeah. Both of them can be used. 😄
> 
> Cool! I'll add the licenses

I meant that both are good, but using a dual-license is not that good, IMO. 😅

**Comment by krishguptadev** [comment]
> > > > > > > > As per the discussion in the discord server, we are gonna allow people to propose articles as a PR. We'll be adding a more restrictive license to make sure the author gets the right.
> > > > > > > 
> > > > > > > 
> > > > > > > Do you think AGPLv3.0+ would be good?
> > > > > > 
> > > > > > 
> > > > > > We need something in the CC line, like we did for Branding
> > > > > 
> > > > > 
> > > > > Those are strict (depends on which one you choose), but not as strict as the AGPLv3.0+, AFAIK.
> > > > 
> > > > 
> > > > But I believe content on the internet is licensed under CC something...
> > > 
> > > 
> > > Yeah. Both of them can be used. 😄
> > 
> > 
> > Cool! I'll add the licenses
> 
> I meant that both are good, but using a dual-license is not that good, IMO. 😅

AGPLv3 for the content for the repo and CC... for the content 🙂

**Pull request closed without merging**
